language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: WMQK8ZvYlmNVdh3r7b2zNQExc1sCyYpbNxbzw7RNEpEhKq3s6GcbN1ynw7niRs7u8U+NMonBQ59wjgU/FnsilU1rsgkQpUPdZ3I4DW+Y4sdqhf1ZJeEUnTJiI49bYm4ZbqqZEt1ifSmqula30ZH2lSp15DPT7xY0xBEJsE++bDQ9yTMtTkU8obnYQgOqgGbI2Vb/63tjbc5uedhNfoUGGM8yCwvg4zEQH/aMaLNIhXkwHGB1Y/k0UZfHWvJLj7baLUglcVfix3o+gPIpowNt4xpvkbMGvwpBLfjb4KzraLptJ/qydHpoQf2XvEF5SiS73LheZlgyVphU4+2tflOLwxcZtrlwnS9WJa/p9oe38EszMblaFu1YtH1fj0nFA51hNpx+R7VRItWvpz3KRsnTYfDtqcl9rpB2n5ZggM4FGY2Hs3cmrOi5dCq7teZtn64gyUkgdzXuu/tf5ltWmW8TfkjR3mpONyCXhbfM3/Wytlx8FROx6XnXMs1rnaVAIfpHxGihiBzQorzuFe+FMIxkO/x2w12W3bbDA/6+Dyr58y2YMXIpqZdUu7B/R69y5tcC2K7u16f7kafvdAlHswMRWrJqTYeBZt5gYoYKCDODfq7Q9lt9rLrt/QoWDEAQKqWk1JZAtE2pFBy3JTkYlJblVzp4pR4btUiyFCOYtJ+ZHWM=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: Jfxd4KlcfhRN0ssWzUf+Ue6gb/kOhuppKoqk74n0n6QATCSJ7ogk1mc4oV+sRHnSMM+ZexRfIdgBoT9IfCYcOtKHSgrLAgjrHcmUeiv09QO/zbvxRKgZaB25LXCqcVsnkZQjeC1Ss+YEEPxBqSfM+jzxdNshyipvaxEk12glvacPVaDUBGHKngcM77er4elAM5oYlprX8yrG8xHdevSyXg7jtF34+j9iFU8LjfXQ+bv+SFc6bT3hjdNHefZeTT1ZquVQhhIe+DCpzz9LiSAOTdi3RFblUJh71HU2/SoW5xpj7/OnYFojMdpXpu7wjJ1g0k6Sqp76C+3tCvrIg3o8a94IOmOlh+rsLlRbxhyJaQA49+09QHmIVNfPmyhc/T4Y04t+WeIJNr5ACZzMK8Nd9Gge6htXMiPhoa7y1bKQbe+URKS8dQQ2EjG7IrKOC0eReVAM7bny77AbWzpfHEPrSyb+hy4SnO1vWgl+/GSC6DBP/Bi9mZc+OuCVD5BHc+78UhVrzJOWH+mwaRqbo6P2sVvzUBvMmeqkan8nIyaikbvEQFinsFJS1gkMIvtzVK574M4QgMokC22Jn1W1mx4fclcnG/qlKimvJ6CN6KKLpK9UYCmgI/yleu1vqnJnYFIRAw758/cgyEz0lS/gZtsyCw987PShP79b8CtD8J7TM9k=
sudo: false
